# Generated by Django 5.1 on 2024-08-11 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventasApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Unidad',
        ),
    ]
