# Generated by Django 5.1 on 2024-08-11 09:32

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0002_rename_categoriaid_producto_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('nro_doc', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('igv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='clientes.cliente')),
                ('tipo_venta', models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='detalle_venta.tipo_venta')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='productos.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='detalle_venta.venta')),
            ],
        ),
    ]
