# Generated by Django 5.1 on 2024-08-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('ruc_dni', models.CharField(max_length=11)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
